"""add recurrence table

Revision ID: 21180492ff73
Revises: 
Create Date: 2023-04-29 13:59:55.109864

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21180492ff73"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurrences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recurrences")
    # ### end Alembic commands ###
