"""add join table between muscle and exercise

Revision ID: 3637c428ce9f
Revises: fd0d26725d6f
Create Date: 2023-04-29 15:00:25.659498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3637c428ce9f'
down_revision = 'fd0d26725d6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises_muscles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('muscle_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises_muscles')
    # ### end Alembic commands ###
