"""added set block table

Revision ID: 77c294385f1d
Revises: 96be49b9b54c
Create Date: 2023-04-29 22:19:34.799132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c294385f1d'
down_revision = '96be49b9b54c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('rest_interval', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_blocks_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('set_block_id', sa.UUID(), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['set_block_id'], ['set_blocks.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_blocks_sets')
    op.drop_table('set_blocks')
    # ### end Alembic commands ###
