"""create set and join table

Revision ID: 96be49b9b54c
Revises: 3637c428ce9f
Create Date: 2023-04-29 19:47:36.878484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96be49b9b54c'
down_revision = '3637c428ce9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reps', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets_exercises')
    op.drop_table('sets')
    # ### end Alembic commands ###
