"""fix workout join table fk

Revision ID: e90526c3af37
Revises: f6e51d9f208c
Create Date: 2023-04-30 00:28:37.434132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90526c3af37'
down_revision = 'f6e51d9f208c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workouts_set_blocks_workout_id_fkey', 'workouts_set_blocks', type_='foreignkey')
    op.create_foreign_key(None, 'workouts_set_blocks', 'workouts', ['workout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts_set_blocks', type_='foreignkey')
    op.create_foreign_key('workouts_set_blocks_workout_id_fkey', 'workouts_set_blocks', 'sets', ['workout_id'], ['id'])
    # ### end Alembic commands ###
