"""add index column to set

Revision ID: f641d18b2c26
Revises: e90526c3af37
Create Date: 2023-04-30 14:34:29.762439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f641d18b2c26'
down_revision = 'e90526c3af37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'index')
    # ### end Alembic commands ###
